name: 'setup-asdf-tools'
description: 'Composite action to setup asdf tools listed in .tool-versions'

runs:
  using: 'composite'
  steps:
    - name: 🤹‍♂️ Install asdf
      uses: asdf-vm/actions/setup@v2

    - name: 🗂️ Cache asdf
      id: cache-asdf
      uses: actions/cache@v3
      with:
        path: ~/.asdf/
        key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}

    - name: 🛠️ Install tools from .tool-versions
      if: steps.cache-asdf.outputs.cache-hit != 'true'
      uses: asdf-vm/actions/install@v2
