version: '3.7'

services:
  express-typescript-skeleton:
    build:
      context: ..
      args:
        - PORT=${PORT}
      dockerfile: ./docker/Dockerfile
    image: ${IMAGE_NAME}:prod
    container_name: express-typescript-skeleton
    restart: always
    depends_on:
      - express-typescript-skeleton-postgres
    env_file:
      - ../.env
    environment:
      - TZ=${TZ}
      - WAIT_HOSTS=express-typescript-skeleton-postgres:5432
    volumes:
      - ${LOGS_VOLUME}:/app/logs
    ports:
      - ${EXTERNAL_PORT}:${PORT}

  express-typescript-skeleton-postgres:
    image: postgres:16
    container_name: express-typescript-skeleton-postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=${TZ}
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  express-typescript-skeleton-pgweb:
    image: sosedoff/pgweb
    container_name: express-typescript-skeleton-pgweb
    restart: always
    depends_on:
      - express-typescript-skeleton-postgres
    environment:
      - PGWEB_DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@express-typescript-skeleton-postgres:5432/${DB_NAME}?sslmode=disable
      - TZ=${TZ}
    ports:
      - ${DB_MANAGER_PORT}:8081

  express-typescript-skeleton-redis:
    image: redis:7
    container_name: express-typescript-skeleton-redis
    restart: always
    command: /bin/sh -c "redis-server --appendonly yes --requirepass ${CACHE_PASSWORD}"
    environment:
      - TZ=${TZ}
    volumes:
      - ${CACHE_VOLUME}:/data
    ports:
      - ${CACHE_PORT}:6379

  express-typescript-skeleton-redis-commander:
    image: rediscommander/redis-commander
    container_name: express-typescript-skeleton-redis-commander
    restart: always
    platform: linux/amd64
    depends_on:
      - express-typescript-skeleton-redis
    environment:
      - REDIS_LABEL=${IMAGE_NAME}-cache
      - REDIS_HOST=express-typescript-skeleton-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${CACHE_PASSWORD}
      - TZ=${TZ}
    ports:
      - ${CACHE_MANAGER_PORT}:8081

networks:
  default:
    name: ${IMAGE_NAME}-network
