#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# The reason we're exporting this variable is because of this issue:
# https://github.com/typicode/husky/issues/968
export FORCE_COLOR=1

npx commitlint --edit $1 ||
(
  echo '✍📤 It seems that the format of the commit does not follow the conventional commit convention. You can also try committing with the "npm run commit" command.';
  false;
)
