#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# The reason we're exporting this variable is because of this issue:
# https://github.com/typicode/husky/issues/968
export FORCE_COLOR=1

echo '🔍🎨 Formating and checking staged files before committing!'

npx lint-staged ||
(
  echo '💀❌ Ooops! Formating and checking process has failed!';
  false;
)

echo '🥳✅ Formating and checking process has been successfully completed!'
